### ISSUE TITLE
Etudier la solution Reveal-ck

### ISSUE THREAD

**Issue by jlandure** [Zenika/zenika-formation-framework#108]
Je suis tombé dessus par hasard : http://jedcn.github.io/reveal-ck/
A voir ce que ça fait par rapport à notre framework. :)

**Comment by hgwood** [comment]
Problème : c'est du Ruby. Je pense pas qu'on puisse demander d'installer ça en plus de Node.

**Comment by hgwood** [comment]
En regardant du plus prêt je dirais que notre framework contient les fonctionnalités de reveal-ck, c'est-à-dire de générer un slide deck à partir d'un ou plusieurs fichiers markdown.
