### ISSUE TITLE
Déploiement continu des PDF sur le drive

### ISSUE THREAD

**Issue by FBerthelot** [Zenika/zenika-formation-framework#110]
J'ai récemment parcouru l'API Google drive et ça m'a donné l'idée du déploiement continu des cahiers PDF sur le drive pour l'imprimeur.

L'API en exemple: https://developers.google.com/drive/v3/web/quickstart/nodejs#step_3_set_up_the_sample
Une tâche gulp est envisageable 😄 

Qu'en pensez-vous ?

**Comment by jlandure** [comment]
Salut,

A voir avec Olivier mais je pensais que passer toutes les formations en mode déploiement continu serait plus intéressant car on peut:
* voir la formation en ligne
* voir les pdfs
cf [l'url des formations](http://app.zenika.com/#/training) sur ZenApp

Si le déploiement n'est pas automatisable pour toutes les formations, alors oui un tâche gulp pourrait être intéressante.

**Comment by FBerthelot** [comment]
Justement, j'en ai parlé avec Olivier (j'ai même fait tilt en le voyant ^^).

Je suis d'accord avec le déploiement continu pour toutes les formations, c'est largement mieux !
Néanmoins, je ne sais pas comment l'imprimeur se débrouille. A voir avec l'imprimeur surtout.

Je pense que cette issue, n'est pas prioritaire. Je l'ai juste créer pour qu'on ai dans notre esprit que c'est possible :)

**Comment by jlandure** [comment]
Yes. Pas de souci. A voir effectivement comment c'est partagé à l'imprimeur...
Je ne sais pas comment est géré le process aujourd'hui et je pense qu'il diffère entre les agences `(impression à Paris != impression à Nantes)`

**Comment by FBerthelot** [comment]
Je viens de parler avec olivier des contraintes imprimeur.

La seul chose dont il a besoin, c'est qu'une personne avec un mail différent de `@zenika.com` puisse accéder aux PDF.

Apparemment ce n'est pas possible actuellement sur les formations en mode déploiement continu.

**Comment by hgwood** [comment]
@olivierhuber @FBerthelot @jlandure Correct me if I'm wrong, but we don't this anymore because we don't print slides anymore, so I'll close.
