### ISSUE TITLE
Compatibilité avec Node 7

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#111]
Gulp 3 et Grunt 0.4 ne seront pas compatibles avec Node 7 car ils utilisent une ancienne version de `graceful-fs`. Si l'on ne veut pas bloquer les consultants avec une "vieille" version de Node ou les forcer à installer nvm, il faudra mettre à jour le build à Grunt 1 et Gulp 4 avant octobre (date prévue de sortie de Node 7). On pourrait d'ailleurs en profiter pour merger les 2 builds en 1.

Plus d'infos : https://github.com/isaacs/node-graceful-fs/issues/64

**Comment by ggerbaud** [comment]
Parfaitement en phase, mais cela nécessite des contributions.

**Comment by Gillespie59** [comment]
Idem pour Node 6. Je viens de tester et cela ne fonctionne pas.

**Comment by hgwood** [comment]
Tu peux préciser ? Normalement Node 6 n'émet qu'un warning du type `fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.`.

**Comment by Gillespie59** [comment]
Voici ce que j'obtiens. 

- je clone une formation (angular2 par exemple)
`nvm use 6.0`
`npm install`

Avec Grunt, j'ai : 

```
>> Tasks directory "/home/emmanuel/Documents/workspace/formation-angular2/node_modules/zenika-formation-framework/node_modules/grunt-sed/tasks" not found.
>> Tasks directory "/home/emmanuel/Documents/workspace/formation-angular2/node_modules/zenika-formation-framework/node_modules/grunt-contrib-connect/tasks" not found.
>> Tasks directory "/home/emmanuel/Documents/workspace/formation-angular2/node_modules/zenika-formation-framework/node_modules/grunt-contrib-watch/tasks" not found.
>> Tasks directory "/home/emmanuel/Documents/workspace/formation-angular2/node_modules/zenika-formation-framework/node_modules/grunt-contrib-clean/tasks" not found.
>> Tasks directory "/home/emmanuel/Documents/workspace/formation-angular2/node_modules/zenika-formation-framework/node_modules/grunt-contrib-copy/tasks" not found.
>> Tasks directory "/home/emmanuel/Documents/workspace/formation-angular2/node_modules/zenika-formation-framework/node_modules/grunt-filerev/tasks" not found.
>> Tasks directory "/home/emmanuel/Documents/workspace/formation-angular2/node_modules/zenika-formation-framework/node_modules/grunt-filerev-replace/tasks" not found.
(node:32105) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Warning: Task "sed" not found. Use --force to continue.
```

**Comment by hgwood** [comment]
Les erreurs qui empêchent la tâche de fonctionner sont les `>> Tasks directory...`. Celles-ci sont du à npm 3. La tâche Grunt n'est compatible qu'avec npm 2. Utilise Gulp à la place.

Le fait qu'il y est un warning `fs: re-evaluating` à cet endroit est un coincidence. C'est un warning qui n'empêche en rien l'exécution.

**Comment by hgwood** [comment]
Suite à #115 on devrait pouvoir se contenter d'upgrader Grunt à 1.0 (en attendant éventuellement #117).

**Comment by hgwood** [comment]
Plus qu'un mois avant la sortie de Node 7. :(

**Comment by hgwood** [comment]
Bonne nouvelle ! 

> graceful-fs below version 4.0 (well, technically *only 2.x and 3.x*) is going to break on Node.js 7.x
-- https://github.com/gulpjs/gulp/issues/1640#issue-153194839

> graceful-fs@3.0.10 was released by @isaacs and that version does not trigger the warning anymore
-- https://github.com/gulpjs/gulp/pull/1760#issuecomment-242213701

Grunt 0.4 dépend de graceful-fs 1.x et Gulp 3 de ^3 donc on est sauf !
