### ISSUE TITLE
Renommer le repo pour coller au nom du package

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#116]
Plus logique, et GitHub s'occupe des redirections.

Et je viens de me tromper en faisant `npm link Formation--Framework` ^^'

**Comment by ggerbaud** [comment]
zenika-formation-framework ?

Github s'occupe de quelles redirections ?

**Comment by hgwood** [comment]
Oui c'est bien ce nom là.

Le nom de repo est dans l'url : https://github.com/Zenika/Formation--Framework. Si tu renommes, alors GitHub fera pointer https://github.com/Zenika/Formation--Framework sur https://github.com/Zenika/zenika-formation-framework. Donc je pense que l'URL git dans les package.json des formations fonctionnera toujours.

Je vais tester.

**Comment by hgwood** [comment]
La doc confirme : https://help.github.com/articles/renaming-a-repository/

**Comment by ggerbaud** [comment]
ok

**Comment by ggerbaud** [comment]
Maintenant ? ou alors dans 15 jours ?

**Comment by hgwood** [comment]
Pourquoi pas maintenant ?

**Comment by ggerbaud** [comment]
C'est fait
