### ISSUE TITLE
Possibilité d'externaliser des slides dans une dépendance

### ISSUE THREAD

**Issue by Gillespie59** [Zenika/zenika-formation-framework#118]
Le Use Case est le suivant. Dans certaines formations (AngularJS et node), nous avons une partie "Rappel JavaScript" qui est commune. Mais pour l'instant, pour la synchroniser, nous devons faire la modification sur les deux repository. 

je ne sais pas si c'est déjà possible dans le framework, mais j'avais en tête d'externaliser cette partie commune dans un sous module, téléchargé via NPM et donc présent dans le répertoire node_modules. Et ainsi inclure dans le fichier slides.json, le chemin vers les fichiers MD que nous désirons inclure 

Vous en pensez quoi ?

**Comment by hgwood** [comment]
Bonne idée.

Le paquet pourrait avoir des slides en md et un fichier `slides.json`, puis les formations pourraient l'inclure dans leur propre fichier `slides.json` en faisant `[..., {"include": "../node_modules/rappels-javascript/slides/slides.json', ...]`.

Potentiel problème : il faut que npm puisse télécharger depuis les repos git privés.

**Comment by jlandure** [comment]
Alors oui c'est intéressant de pouvoir importer les slides depuis une dépendance et effectivement ça pose "problème" pour les repos privés. (on avait passé le projet `fmk-formation` en public pour cette raison)
Après si cela concerne uniquement la formation "rappels-js", à voir si on ne peut pas passer le repo en public.

**Comment by Gillespie59** [comment]
Pour ma part, je préfère plutôt généraliser . Mais je comprend bien le problème :s. Dommage ;)
je clos.
