### ISSUE TITLE
Build auto de l'image Docker et push sur Docker Hub

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#121]
latest => master
tag => tag

**Comment by jlandure** [comment]
Done sur le hub docker! 👍 

<img width="1226" alt="capture d ecran 2016-07-29 a 11 51 58" src="https://cloud.githubusercontent.com/assets/525974/17244621/12e091a6-5583-11e6-994c-3aec8b1785d4.png">


J'ai créé aussi un groupe `formationframework` avec @hgwood et @ldez en admin pour pouvoir modifier les ["Build settings"](https://hub.docker.com/r/zenika/formation-framework/~/settings/automated-builds/)
