### ISSUE TITLE
Baser l'image Docker sur Alpine

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#122]
Cf https://hub.docker.com/r/zenika/alpine-node/

**Comment by zigarn** [comment]
```
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
zenika/alpine-node           latest              168eace2436b        4 months ago        235.8 MB
node                         7.2-alpine          164dad592f49        36 hours ago        55.3 MB
zenika/formation-framework   v2.0.1              e0a90f5549af        13 hours ago        814.3 MB
zenika/formation-framework   alpine              b7b446444ee1        33 seconds ago      212.3 MB
```

**Comment by hgwood** [comment]
Pourquoi `node:7.2-alpine` est-elle si grosse comparé à `zenika/alpine-node` ?

**Comment by jlandure** [comment]
cf https://hub.docker.com/r/zenika/alpine-node/
Layers:
* alpine:3.4 5 MB
* g++ 147 MB (needed for node-sass)
* git 17 MB (needed to checkout some repo outside npm)
* nodejs 27 MB
* python 38 MB (needed for node-sass)

Après ils ont fait évolué la officielle `node:7.2-alpine` donc peut-être que la `zenika/alpine-node` n'est plus intéressante. A checker 👍

**Comment by hgwood** [comment]
OK. Je ferme cette issue puisque https://github.com/Zenika/zenika-formation-framework/pull/136

**Comment by zigarn** [comment]
Je pense simplement que l'image officielle fasse du nettoyage des dépendances juste après l'installation :

```
[...]
apk add --no-cache --virtual .build-deps \
        binutils-gold \
        curl \
        g++ \
[...]
&& apk del .build-deps \
[...]
```

```
$ docker history zenika/alpine-node
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
168eace2436b        4 months ago        /bin/sh -c #(nop) WORKDIR /usr/src/app          0 B                 
<missing>           4 months ago        /bin/sh -c mkdir -p /usr/src/app                0 B                 
<missing>           4 months ago        /bin/sh -c apk add --update --no-cache make g   231 MB              
<missing>           5 months ago        /bin/sh -c #(nop) ADD file:852e9d0cb9d906535a   4.799 MB      

$ docker history node:7.2-alpine
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
164dad592f49        37 hours ago        /bin/sh -c #(nop)  CMD ["node"]                 0 B                 
<missing>           37 hours ago        /bin/sh -c adduser -D -u 1000 node     && apk   50.5 MB             
<missing>           6 days ago          /bin/sh -c #(nop)  ENV NODE_VERSION=7.2.0       0 B                 
<missing>           2 weeks ago         /bin/sh -c #(nop)  ENV NPM_CONFIG_LOGLEVEL=in   0 B                 
<missing>           6 weeks ago         /bin/sh -c #(nop) ADD file:7afbc23fda8b0b3872   4.803 MB            
```

**Comment by jlandure** [comment]
C'est surtout que la node:alpine n'avait pas G++ et python avant ^^
mais effectivement dans le [Dockerfile](https://github.com/nodejs/docker-node/blob/master/7.2/alpine/Dockerfile)
On voit que les 'tool' sont bien ajoutées:
```
    && apk add --no-cache --virtual .build-deps \
        binutils-gold \
        curl \
        g++ \
        gcc \
        gnupg \
        libgcc \
        linux-headers \
        make \
        python \
```

**Comment by zigarn** [comment]
Mais surtout installé en [virtual-packages](https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md#virtual-packages) puis [supprimés](https://github.com/nodejs/docker-node/blob/master/7.2/alpine/Dockerfile#L40) :

```
apk del .build-deps 
```

**Comment by jlandure** [comment]
Oui pour sûr, j'avais créé la `zenika:alpine-node` en 10min cet été dans avoir regarder pour nettoyer la distrib. ^^

Pour info, il manque toujours `git` dans la `node:alpine` officielle pour info et c'est gênant je trouve pour les projets. Pour les formations, on en a p'être pas besoin mais pour les projets, c'est fréquent de forker un repo et de pointer dessus en attendant l'acceptation de la PR.

**Comment by zigarn** [comment]
On pourrait installer `git` dans le Dockerfile de ZFF effectivement.

**Comment by jlandure** [comment]
Non, le mieux serait de garder notre `zenika:alpine-node` en se basant sur la `node:alpine` et ajouter uniquement `git` + nettoyage

**Comment by zigarn** [comment]
Plus de nettoyage nécessaire du coup, non ?

**Comment by jlandure** [comment]
j'ai pas compris 😀

**Comment by zigarn** [comment]
Ben si on ne fait qu'installer git en plus, il n'y a rien de plus à nettoyer.
