### ISSUE TITLE
publier l'image docker en version 1.0.1

### ISSUE THREAD

**Issue by gmembre-zenika** [Zenika/zenika-formation-framework#124]
Il serait bien de publier l'image docker en 1.0.1

**Comment by hgwood** [comment]
Les builds auto sont configurés sur le hub docker mais ça ne marche pas. Je ne sais pas quoi faire de plus. :(

**Comment by hgwood** [comment]
OK j'ai lancé un build manuel.

**Comment by hgwood** [comment]
https://hub.docker.com/r/zenika/formation-framework/builds/
