### ISSUE TITLE
theme en 16:10

### ISSUE THREAD

**Issue by gmembre-zenika** [Zenika/zenika-formation-framework#125]
De plus en plus d'écran / retroprojecteur sont très large, ca serait bien de pouvoir en bénéficier !

**Comment by hgwood** [comment]
Je me demande si le nouveau thème ne prend pas ça en charge. @kepennar ?

**Comment by hgwood** [comment]
Non le nouveau thème ne prend pas ça en charge.

**Comment by hgwood** [comment]
Le problème c'est que le contenu actuel des formations n'est pas fait pour :/

**Comment by gmembre-zenika** [comment]
Je ne dis pas de basculer toute nos formations sur ce theme mais d'avoir la possibilité de choisir le passage en 16:10 et d'adapter ensuite les supports en conséquence.
