### ISSUE TITLE
Génération PDF impossible sur MAC OSX

### ISSUE THREAD

**Issue by CapsHil** [Zenika/zenika-formation-framework#139]
Via Docker, c'est visiblement le path qui est mal généré. Une fois mis en dur dans run.sh, ça tourne, il dit que c'est ok, mais rien n'est généré

La génération directement avec Grunt ne fonctionne visiblement pas non plus.

<img width="695" alt="screen shot 2016-12-15 at 14 59 18" src="https://cloud.githubusercontent.com/assets/6097579/21233855/14716032-c2f1-11e6-9c72-ef7e9941e0f0.png">

**Comment by hgwood** [comment]
Utilises-tu Docker for Mac ou une VM ?

**Comment by CapsHil** [comment]
J'utilise Docker for Mac

**Comment by hgwood** [comment]
Est-ce que tu peux me donner :
- le chemin absolu du dossier où tu exécutes la commande
- la conf File Sharing de Docker

**Comment by CapsHil** [comment]
Chemin absolu : /Users/Zenika/Workspace/formations/formation-microservices-developpeurs/
Conf File Sharing : 
<img width="65" alt="screen shot 2016-12-16 at 15 29 59" src="https://cloud.githubusercontent.com/assets/6097579/21266061/b3369206-c3a4-11e6-8fcb-3d7aa96892c5.png">

**Comment by hgwood** [comment]
Tu peux essayer de créer le dossier `PDF` à l'intérieur de `formation-microservices-developpeurs` puis relancer la commande ?

**Comment by CapsHil** [comment]
Déjà essayé, même résultat

**Comment by hgwood** [comment]
J'appelle les contributeurs de `run.sh` à la rescousse : @l0rd @looztra @RelikDream @gmembre-zenika @zigarn @yyekhlef @vdemeester @srevereault @coliss86

**Comment by gmembre-zenika** [comment]
le pb provient du double / que l'on ajoute lors du mapping de volume avec docker : 
voici ce que l'on a aujourd'hui : 
```
docker run -it --rm -v //Users/guillaume/projets/Formation-microservices-developpeurs/Gruntfile.js:/data/Gruntfile.js -v [...] zenika/formation-framework:0.4.6 grunt pdf
```
alors que l'on devrait écrire : 
```
docker run -it --rm -v /Users/guillaume/projets/Formation-microservices-developpeurs/Gruntfile.js:/data/Gruntfile.js -v [...] zenika/formation-framework:0.4.6 grunt pdf
```
(Suppression du / en trop devant "Users")

Une correction possible du ```run.sh``` serait : 
```
export VOLUME_SLIDES="$PWD/Slides/:/data/Slides/"
```
à la place de 
```
export VOLUME_SLIDES="/$PWD/Slides/:/data/Slides/"
```
mais je ne sais pas si cela marchera sous windows, qq1 pour confirmer ?

**Comment by hgwood** [comment]
Perso sous Windows je met la variable d'environnement `MSYS_NO_PATHCONV` à `1` pour que Git Bash se fasse pas de traduction des chemins avant de les passer à Docker. Ca marche parce que Docker tourne dans une VM Linux qui utilise les mêmes chemins qui la machine Windows mais en mode Linux (`/c/Users/...`) et les dit chemins sont montés par VirtualBox dans la VM. Tout cela est pas défaut avec Docker Machine sous Windows, donc je pense que c'est une bonne solution pour ce cas là. Maintenant le problème c'est : et pour Docker for Windows ?

Après je pense qu'on a plus de gens sous Docker Machine et Docker for Mac et que Docker for Windows donc on peut peut-être se permettre de faire cette modification.

**Comment by hgwood** [comment]
OK je viens de voir qu'en plus Docker for Windows n'est disponible que sur Windows 10 Pro, que personne n'a.

**Comment by hgwood** [comment]
@CapsHil tu pourrais tester la solution de @gmembre-zenika ?

**Comment by CapsHil** [comment]
Je confirme, la méthode de @gmembre-zenika fonctionne sur Mac, il suffit bien de supprimer tout les `/` au début des PATH qui commencent par `$PWD`

**Comment by CapsHil** [comment]
Du coup un simple `if` sur un `uname -s` peut régler le problème

**Comment by hgwood** [comment]
@CapsHil Tu ferais une petite PR sur https://github.com/Zenika/Formation--Modele ?

**Comment by hgwood** [comment]
Devrait être corrigé avec https://github.com/Zenika/Formation--Modele/pull/121
