### ISSUE TITLE
Templates de slides

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#142]
Créer une bibliothèque de slides avec des layouts souvent utilisés, et dont on peut copier le code markdown facilement. Le but est de faciliter la vie de l'auteur de formation.

# Idées
- Un fichier Markdown sur GitHub (dans le repo ou le wiki) avec des screenshots des slides et le code en-dessous ou à côté.
- Un mini-site avec un aperçu des slides et un bouton pour copier le code sous-jacent.

**Comment by gmembre-zenika** [comment]
dans le Formation--modele, il y a déjà tout cela : 
https://zenika-formation-modele-dot-zen-formations.appspot.com/slides.html#/1

que faut il de plus ?

**Comment by hgwood** [comment]
Bonne question. Je ne sais plus. Je pense qu'on peut fermer.
