### ISSUE TITLE
Build CircleCI en timeout lors de la phase de deploy

### ISSUE THREAD

**Issue by zigarn** [Zenika/zenika-formation-framework#153]
https://circleci.com/gh/Zenika/formation-git/27

**Comment by hgwood** [comment]
C'est corrigé.

- Build : https://circleci.com/gh/Zenika/formation-git/29
- Mini-site (`master`) : http://master-dot-formation-git-dot-zen-formations.appspot.com/
- Readme mis à jour : 

Ce que j'ai fait :
- Modifier le nom dans le package.json pour que ce soit un nom valide de service AppEngine : https://github.com/Zenika/formation-git/commit/bf3bbce940f3209e2fd5da2430c985d169d631e0
- Exécuter `node ic.js formation-git` avec les variables d'environnement qui vont bien (voir readme du framework)
- Mettre à jour le readme avec les nouvelles URL AppEngine : https://github.com/Zenika/formation-git/commit/e18ca8e0854909729605262f097f774d393441ba

Pour l'instant il n'y a que moi et Julien qui avons la clé d'autorisation AppEngine pour faire l'étape 2 mais on va améliorer pour que ça puisse être n'importe qui. :)

N'hésite pas si tu as des questions.

**Comment by hgwood** [comment]
Tout ceci est du cette transition : https://github.com/Zenika/zenika-formation-framework/issues/146
