### ISSUE TITLE
CI does not use the latest framework version

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#165]
CircleCI uses a cache on `npm install`s so the PDF rendering does not always use the latest framework version. Questions:

- Should we do something about it?
- What can we do about it?
- What is the ttl of the cache?

In the meanwhile, it is possible to manually ask Circle to retry a build without the cache.

**Comment by olivierhuber** [comment]
I hate cache

**Comment by olivierhuber** [comment]
There are only two hard things in Computer Science: **cache invalidation** and naming things.
_- Phil Karlton_

**Comment by olivierhuber** [comment]
Ok seriously can we remove the cache altogether ... For me it's unusable now since i can't even have the latest version of my PDF

**Comment by hgwood** [comment]
[It does seem do be possible to disable the cache](https://circleci.com/docs/1.0/how-cache-works/). @olivierhuber Do you have access to CI builds? From there you can trigger rebuilds without cache. Not ideal I know but useful.

**Comment by hgwood** [comment]
Idea: have a script that calls the CircleCI API to rebuild all projects without cache, and have this script be called in npm's `postversion` script. This would rebuild everything every time a new framework version is released.

**Comment by jlandure** [comment]
Or a Bot on Slack to do it 😉 
The trigger will be:
- a new release on the repo
- a specific action from slack
