### ISSUE TITLE
PhantomJS alternatives

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#168]
- PhantomJS 1.9 does not work on MacOS Sierra (#163)
- PhantomJS 2.1 does not print correct PDFs consistently on all OSes (#164)

What can we do?

- **Wait for Chrome 59** (includes Headless Chrome with PDF printing support). Getting Started: https://developers.google.com/web/updates/2017/04/headless-chrome
- ~~Wait for PhantomJS 2.5 ([no release date](https://groups.google.com/forum/#!topic/phantomjs/eVa1xtbnxzs))~~ [PhantomJS abandoned](https://groups.google.com/forum/m/#!topic/phantomjs/9aI5d-LDuNE)
- ~~Wait for [Headless Chrome](https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md) to support [PDF printing](https://bugs.chromium.org/p/chromium/issues/detail?id=603559)~~
- Evaluate [PDF generation in Electron](https://electron.atom.io/docs/api/web-contents/#contentsprinttopdfoptions-callback)
- Evaluate https://github.com/Janpot/electron-pdf
- Evaluate https://github.com/kapouer/node-webkitgtk
- Could we transform the markdown into a [PDFKit](http://pdfkit.org/) script?
- Enforce PDF generation to be done in Docker and only support that

**Comment by hgwood** [comment]
The more I think about it the more the last option makes sense. It would simplify the framework quite a bit. The main drawback is that Docker become a requirement to generate PDFs, but since we now have a CI that does that, I don't see why most users would want to generate PDFs locally. However, we need to make sure the CI is capable of running Docker properly.

**Comment by bpetetot** [comment]
FYI : Native support of docker available in [Circle CI 2.0](https://circleci.com/beta-access/)(beta access only for now)

**Comment by hgwood** [comment]
@bpetetot I'm not sure it means it will be able to run docker. Rather, that the build can be run inside a docker container.

**Comment by hgwood** [comment]
Headless Chrome seems like the go-to solution now.

**Comment by hgwood** [comment]
Note: moving from Phantom allows us to drop the `promise` and `setimmediate` polyfills.

**Comment by hgwood** [comment]
Closing in favor of #185.
