### ISSUE TITLE
VERSION on PDF is not replaced

### ISSUE THREAD

**Issue by olivierhuber** [Zenika/zenika-formation-framework#169]
I just generated the formation-jpa PDF with `./run.sh pdf` and seemed to work fine but the VERSION on the first slide bottom right is not replaced
It does work if I use `grunt` though so the problem comes from the Docker image i guess

**Comment by hgwood** [comment]
Looks like the `pdf` task (run by `run.sh`) does not depend of the `sed` task (which replaces `VERSION`) in `Gruntfile.js`. Definitely a bug. In the meantime you can get your PDFs from the CI builds. They should be available at http://zen-formations.appspot.com/ in just a moment.

**Comment by olivierhuber** [comment]
Bon si je remplace dans le `run.sh` le `grunt pdf` par `grunt package` ca marche (merci Hugo) mais c'est effectivement une solution temporaire. Donc l'issue reste ouverte mais au moins je suis débloqué la dessus.

**Comment by hgwood** [comment]
Fixed in 2.3.2.
