### ISSUE TITLE
Document "support for remotes"

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#173]
Document this feature: #170.

**Comment by moreau-nicolas** [comment]
Tell me where to document the feature and I'll do it. :-)

**Comment by hgwood** [comment]
Here would be the best I think: https://github.com/Zenika/Formation--Modele

Could you add a paragraph above "Commandes RevealJS" explaining the feature? Also add the keyboard shortcut to "Commandes RevealJS" (maybe rename this paragraph "Raccourcis clavier" in the process.
