### ISSUE TITLE
Empty slides

### ISSUE THREAD

**Issue by FBerthelot** [Zenika/zenika-formation-framework#176]
En version 2.5.0, certains slides sont vides. Cf formation typescript issue 122

**Comment by FBerthelot** [comment]
Je préconise de passer à yarn pour (le déploiement continue) histoire de ne pas casser les différents builds, ou un shrinkwrap :)

**Comment by FBerthelot** [comment]
La génération des pdfs marchait en version 2.3.0 voiloù

**Comment by hgwood** [comment]
Pas de yarn parce qu'on veut que les formations soient toujours buildées avec la dernière version compatible du framework (cf #165).

**Comment by hgwood** [comment]
Fixed in 2.5.1.
