### ISSUE TITLE
Mauvaise intégration pour les <strong> et <em>

### ISSUE THREAD

**Issue by Gillespie59** [Zenika/zenika-formation-framework#180]
Je me suis aperçu hier que le thème était incorrect pour les balises `<em>` et `<strong>`. 

la `font-style: italic` doit être défini sur la balise `em`

**Comment by hgwood** [comment]
Duplicate of #72.

I know it can be surprising but there is nothing *wrong* about this. The theme is designed like this purposefully to avoid bold text.

**Comment by Gillespie59** [comment]
ok je n'avais pas vu cette issue. On ferme alors.
