### ISSUE TITLE
Configure grunt to customize slides location

### ISSUE THREAD

**Issue by Nebulis** [Zenika/zenika-formation-framework#189]
For instance, when translating training we have a specific folder (Slides_en) where translated slides are located.

For the moment it's impossible to display these slides using grunt

**Comment by hgwood** [comment]
I suggest using `grunt.option()` like with the port.

**Comment by hgwood** [comment]
@Nebulis Are you still planning on implementing this? If not you lay unassign yourself to signal this is open for contributions. :)
