### ISSUE TITLE
PDFs do not correctly render SVGs and code fonts

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#196]
@tonyb1974 says he can't generate PDFs. Could you tell us more about this @tonyb1974?

- What commands are you running?
- What error are you getting?

**Comment by tonyb1974** [comment]
Bonjour Hugo,

J'arrive bien à générer des PDFs via la commande "grunt pdf".

Mes problèmes sont que:
- les images SVG n'apparaissent pas 
- Les blocs de code voient les polices de caractère tronquées en hauteur.Comme si le haut de chaque ligne de code était masqué.

Mes versions d'outil:
npm -v   ---> 2.14.12
node -v ---> 4.2.6

Il paraît qu'il existe un nouveau mode de génération des pdf qui ne passe plus par phantomjs mais par chrome. 
Ce nouveau fonctionnement est-il mis en place sur les 3 formations Elasticsearch ?
Peux-tu mettre à jours ces trois formations sur ce point ?

Merci pour ton aide,
Tony

**Comment by hgwood** [comment]
- Pour les SVG, oui ce n'est pas supporté pour le moment. Il faut les convertir dans un autre format.
- Pour la police de code, je ne vois pas de problème sur les PDF actuels (https://formation-elasticsearch-dot-zen-formations.appspot.com/pdf/Zenika-Formation-formation-elasticsearch-Slides.pdf). Est-ce que cela arrive seulement sur les PDF que tu génères toi-même ? Est-ce tu peux montrer un screenshot ou carrément le PDF ?

Il existe effectivement une nouvelle manière de générer les PDF, mais elle n'a pas encore été publiée. Je vais voir si je peux publier une version expérimentale.

**Comment by tonyb1974** [comment]
Pour les svg, c'est problématique ... Olivier H pensait que c'était bon ...
Peux-tu activer ça sur la branche suivante:
https://github.com/Zenika/formation-elasticsearch/tree/elasticsearch-5.x

Ce sera un bon test.

Pour le PDF, le voici:
[Zenika-Formation-formation-elasticsearch-Slides.pdf](https://github.com/Zenika/zenika-formation-framework/files/1111658/Zenika-Formation-formation-elasticsearch-Slides.pdf)

Slide 88 par exemple...

Merci pour ton aide

**Comment by hgwood** [comment]
- Je précise pour les SVG : ce n'est pas supporté dans la version actuelle mais ça devrait fonctionner avec la version expérimentale.
- Je ne vois pas de soucis avec la slide 88 :
![image](https://user-images.githubusercontent.com/1656170/27686768-74e23f9a-5cd4-11e7-8c4f-8869791ee38a.png)

**Comment by tonyb1974** [comment]
Chez moi ça donne ça ... ![image](https://user-images.githubusercontent.com/2788704/27687333-bd110718-5cd6-11e7-96f3-bbc93438a093.png)

Comment activer cette fonctionnalité expérimentale ?

**Comment by hgwood** [comment]
OK du coup c'est difficile à dire si le PDF qui est en faute ou le lecteur PDF qui tu utilises. :/

Pour la version expérimentale, je suis entrain de la publier pour que tu puisses y avoir accès.

**Comment by tonyb1974** [comment]
Je n'avais jamais eu de problème avant ni avec d'autres pdf. Par contre, ça fait un moment que je n'avais testé sur nos cours... 
Désolé de ne pas pouvoir être plus précis et ton test me permet au moins de savoir que je pourrai proposer de changer de lecteur PDF aux stagiaires. 

Merci encore,
Tony

**Comment by hgwood** [comment]
Pour info mon lecteur de PDF c'est Chrome.

Alors pour l'impression PDF expérimentale, tu fais comme ça :
- tu te places dans le répertoire de la formation
- tu fais `npm install zenika-formation-framework@pdf-chrome`
- tu fais `npm start pdf`

Dit-moi ce que ça donne :)

**Comment by tonyb1974** [comment]
Fonctionne sous Firefox également. Je n'y avais pas pensé ...

Pour la commande que tu m'as fournie, il y a un problème dont voici les traces...
npm start pdf

> formation-elasticsearch@1.1.0 start /home/tony/projets/formations/formation-elasticsearch
> grunt "pdf"

Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Warning: Task "pdf" not found. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.4.0-79-generic
npm ERR! argv "/home/applications/nodeJs/bin/node" "/home/applications/nodeJs/bin/npm" "start" "pdf"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! formation-elasticsearch@1.1.0 start: `grunt "pdf"`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the formation-elasticsearch@1.1.0 start script 'grunt "pdf"'.
npm ERR! This is most likely a problem with the formation-elasticsearch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt "pdf"
npm ERR! You can get their info via:
npm ERR!     npm owner ls formation-elasticsearch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tony/projets/formations/formation-elasticsearch/npm-debug.log
tony@Shirka:~/projets/formations/formation-elasticsearch$ grunt pdf
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Warning: Task "pdf" not found. Use --force to continue.

Aborted due to warnings.

**Comment by hgwood** [comment]
Ah j'ai oublié de te dire qu'il te faut Chrome Canary. :)

**Comment by tonyb1974** [comment]
Aïe, non dispo sous Linux ...

De manière générale, le moins de prérequis est un plus surtout qu'installer un "malware" ne m'enchante guère du tout du tout ... :-(

**Comment by hgwood** [comment]
- Garde tes opinions et ton attitude passive-aggressive au placard s'il te plait. J'essaye de t'aider. :)
- Convertir du HTML en PDF c'est compliqué, ça demande un navigateur bien fait. Actuellement on dépend d'un vieux truc déprécié. Pour l'instant on s'est penché sur Chrome parce qu'ils sont très moteurs sur le sujet du pilotage du navigateur via script, mais bien sûr on pourrait envisager d'autres navigateurs. Je t'encourage à ouvrir des issues pour proposer des choses (de manière constructive).
- Tu peux utiliser Chromium si tu préfères, autant que je puisse en juger.
- Pour Canary c'est pas grave, les channels Beta ou Dev feront l'affaire : https://www.chromium.org/getting-involved/dev-channel. Il faut simplement avoir la version 60 ou plus.

**Comment by tonyb1974** [comment]
Ok pour le premier point, je n'avais pas écris ça pour te heurter, j'ai simplement de plus en plus de mal avec les GAFAs...
J'essaierai donc d'être plus constructif

Merci pour les infos d'installation je vais regarder ça.

**Comment by hgwood** [comment]
Eh tu sais en fait y'a pas besoin de tout ça. Tu as juste à lancer `grunt`, ouvrir les slides dans Chrome/Chromium (la version actuelle, pas besoin de beta), ajouter `?print-pdf` à la fin de l'URL puis imprimer et choisir une sortie au format PDF.

**Comment by hgwood** [comment]
Je pars en congés ce soir pour 3 semaines. Si jamais tu as besoin de plus d'aide je te redirige vers @jlandure. a+

**Comment by hgwood** [comment]
@tonyb1974 as-tu réussi à faire ce que tu voulais ?

**Comment by hgwood** [comment]
To sum up: SVGs are not rendered when slides are rendered through the automatic PDF generation pipeline, as of 2.6. They will be supported in the future: #185. However, it is possible to have SVG rendered when generating PDF manually using Chrome or Firefox.

I'm closing since this will be fixed with #185.
