### ISSUE TITLE
Impossible de lancer run.sh formation-elasticsearch depuis master

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#213]
Message from @ppolyte 

je viens de récupérer la branche master et j'ai un souci avec la generation des pdfs 

Contexte :
je suis sous windows et j'utilise docker. tout mon disque est un dossier partagé.

je me connecte dans mon container et je veux lancer ./run.sh clean pdf
```
docker-machine ssh default
cd formation-elasticsearch
./run.sh clean pdf =>  ERREUR
```
ex:
``` 
docker@default:/c/dev/prjs/git-zenika/formation-elasticsearch$ ./run.sh clean pdf
-sh: ./run.sh: not found
```
ou
``` 
docker@default:/c/dev/prjs/git-zenika/formation-elasticsearch$ sh run.sh  pdf
run.sh: line 46: syntax error: bad function name
```

peux tu m'aider ?

**Comment by hgwood** [comment]
Do you have bash on the Windows host? You should have it if you have Git. If so, can you try running `run.sh` directly from Windows instead of inside the docker machine?

**Comment by ppolyte** [comment]
yes, i have git bash. I try to run directly run.sh as you told me. it is still not working. see errors below.

===========
from docker quickstart terminal (opened as admin)
prisca@PRISCA-PC-PRO /c/dev/prjs/git-zenika/formation-elasticsearch (master)
$ ./run.sh clean pdf
Arret et suppression du conteneur existant (formation-elasticsearch)
Error response from daemon: No such container: formation-elasticsearch
prisca@PRISCA-PC-PRO /c/dev/prjs/git-zenika/formation-elasticsearch (master)
$
OR

from git bash terminal (opened as admin)

prisca@PRISCA-PC-PRO /c/dev/prjs/git-zenika/formation-elasticsearch (master)
$ ./run.sh clean pdf
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.31/containers
/json?all=1: open //./pipe/docker_engine: Le fichier spcifi est introuvable. In
the default daemon configuration on Windows, the docker client must be run eleva
ted to connect. This error may also indicate that the docker daemon is not runni
ng.
Aucun conteneur identifié à nettoyer (formation-elasticsearch)
Génération du pdf
c:\Program Files\Docker Toolbox\docker.exe: error during connect: Post http://%2
F%2F.%2Fpipe%2Fdocker_engine/v1.31/containers/create: open //./pipe/docker_engin
e: Le fichier spcifi est introuvable. In the default daemon configuration on Win
dows, the docker client must be run elevated to connect. This error may also ind
icate that the docker daemon is not running.
See 'c:\Program Files\Docker Toolbox\docker.exe run --help'.
prisca@PRISCA-PC-PRO /c/dev/prjs/git-zenika/formation-elasticsearch (master)
$

==========

what can I do now ?

**Comment by hgwood** [comment]
Can you try `./run.sh pdf` (without `clean`) from the docker quickstart terminal?

**Comment by ppolyte** [comment]
it worked.

I have a new folder PDF which contains the pdf files.

thanks.

**Comment by hgwood** [comment]
I'm glad I could help out.
