### ISSUE TITLE
Upgrade to the new Zenika theme

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#214]
Powerpoint models have been updated to a new theme that is consistent with zenika.com. The same should be done with HTML training material.

@FBerthelot @Swiip Could you handle this at Aya and submit a pull request?

**Comment by FBerthelot** [comment]
Hello,

Unfortunately I cannot do this right now. I will be available around December.
Swiip is on vacation right now. Let see if he can handle this when he get back next week.

Good luck,

**Comment by hgwood** [comment]
OK. Thanks for the answer. @olivierhuber you may want to assign somebody else. I'm going investigate availability in Nantes right away. I must though I'm not sure it must treated as an emergency. I'll still mark it as having priority.

**Comment by hgwood** [comment]
@EmrysMyrddin might have some availability to do this at the end of this week. I'll assign him for now.

**Comment by hgwood** [comment]
Powerpoint model: https://drive.google.com/drive/u/0/folders/0Bx7qOCA6OCsSdnBFVWNJNUU0a2s
