### ISSUE TITLE
Write mathematical formulas

### ISSUE THREAD

**Issue by bnouyrigat** [Zenika/zenika-formation-framework#218]
Display math equations in your presentation

**Comment by hgwood** [comment]
What is not working after applying this commit: https://github.com/bnouyrigat/zenika-formation-framework/commit/b04e81f799e25fa887ccecf02850f83e6723823c

**Comment by bnouyrigat** [comment]
I build a specific Docker image:
```bash
$ docker build -t tensorflow-formation:mathjax .
```

This container doesn't start:
```bash
$ docker logs formation-deeplearning-tensorflow 
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module './pdf/generate-pdf-with-chrome'
Warning: Task "displaySlides" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by hgwood** [comment]
I think the problem you are seeing here is unrelated to mathjax. There seems to be an inconsistency in your setup. The module `./pdf/generate-pdf-with-chrome` does not appear before framework v3, si it looks like you are running framework v3, but your `run.sh` seems not to be properly migrated to be compatible with v3. See https://github.com/Zenika/zenika-formation-framework/blob/master/CHANGELOG.md#migrating

**Comment by bnouyrigat** [comment]
I pick the two commits from the link above and now it's OK.
Thx
