### ISSUE TITLE
Changer le repo "Modele" en template

### ISSUE THREAD

**Issue by jlandure** [Zenika/zenika-formation-framework#244]
Nouvelle feature de github:
https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/

<img width="725" alt="Capture d’écran 2019-07-22 à 10 12 29" src="https://user-images.githubusercontent.com/525974/61616617-3ad39880-ac69-11e9-98e3-625d66633818.png">

**Comment by hgwood** [comment]
Good idea! Done.
