### ISSUE TITLE
Générer le cahier d'exercice en html

### ISSUE THREAD

**Issue by patou** [Zenika/zenika-formation-framework#246]
Le cahier d'exercice n'est plus imprimer, une version html permettrait d'éviter les problèmes de ligne de code trop longue qui ne sont pas copiable.
Les slides pourrait ainsi faire un lien direct vers le TP.

**Comment by hgwood** [comment]
Tu as un exemple de ligne de code trop longue ?

**Comment by patou** [comment]
@hgwood dans la formation microsevices developpeurs

`docker run --rm --name myelastic -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "cluster.routing.allocation.disk.threshold_enabled=false" -e "cluster.name=elasticsearch" docker.elastic.co/elasticsearch/elasticsearch:6.7.0`

**Comment by patou** [comment]
Et, c'est pareil, un copié collé d'un code maven
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
</dependency>
```
Ajoute des caractères invalide, et ne fonctionne pas.

**Comment by patou** [comment]
https://github.com/Zenika/formation-microservices-developpeurs/blob/master/CahierExercices/TP02.md

**Comment by hgwood** [comment]
OK donc 2 issues à mon avis:
- le CSS appliqué aux PDF ne désactive pas l'overflow sur les blocs `pre`
- ce serait intéressant d'avoir le cahier au format html

**Comment by hgwood** [comment]
Pour récupérer le html ça devrait être facile, tout est dans le gruntfile.

Le HTML est généré [ici](https://github.com/Zenika/zenika-formation-framework/blob/master/Gruntfile.js#L351) donc suffirait de l'écrire dans un fichier, à la manière du PDF [ici](https://github.com/Zenika/zenika-formation-framework/blob/master/Gruntfile.js#L367).

Tu pourrais tester et faire une PR ?
