### ISSUE TITLE
Impossible d'exécuter sur Docker sous Windows

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#250]
Rapporté par @moreau-nicolas 

> Aujourd'hui sous Windows il est :
> - Impossible de générer les slides dans un conteneur.
> - Impossible de démarrer un conteneur "dev".
> - Impossible de démarrer un conteneur "prod".
>
> Apparemment, le conteneur n'arrive pas à trouver le Gruntfile.
>
> Je pense que c'est lié à un changement récent du fonctionnement de docker pour Windows qui utilise désormais des chemins de dossiers partagés et non plus de disques en entier. 
>
> Quel que soit le ou les dossiers que je partage le résultat est le même : le conteneur s'arrête aussitôt. :(
>
> Heureusement, l'utilisation de Node directement sur le poste fonctionne.

@moreau-nicolas pourrais-tu fournir
- les commandes exécutées 
- les erreurs exactes 
- la ou les formations sur lesquels tu testes

**Comment by hgwood** [comment]
Essai sur mon poste sur la formation React 

```
$ MSYS_NO_PATHCONV=1 docker run -it --rm -v $(pwd)/PDF:/data/PDF -v $(pwd):/data zenika/formation-framework grunt pdf
grunt-cli: The grunt command line interface (v1.3.2)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

https://gruntjs.com/getting-started
```

Il semble que la grunt-cli requiert que grunt soit installé comme dépendance locale alors que ce n'est pas le cas avant.

**Comment by hgwood** [comment]
@moreau-nicolas Tu peux peut-être essayer avec https://github.com/Zenika/sensei pour voir. :)

**Comment by moreau-nicolas** [comment]
Alors, j'ai pu creuser un peu, j'ai trouvé.
C'est un problème lié en partie à la conversion de chemin MSYS2.
J'avais omis le MSYS_NO_PATHCONV=1.
Si on supprime tous les partages et qu'on relance `MSYS_NO_PATHCONV=1 ./run.sh dev` il suffit d'accepter les différentes invites qui s'affichent pour les fichiers `Gruntfile.js`, `package.json`, `CahierExercices/`, `Slides/` et tout fonctionne.

Du coup le problème vient de la détection de l'exécution au sein de MSYS2. Je vais faire une PR.
Du coup @hgwood il faut que je fasse ma PR sur [Zenika/zenika-formation-framework](Zenika/zenika-formation-framework) ?

**Comment by hgwood** [comment]
Merci pour ta PR https://github.com/Zenika/training-template/pull/142
