### ISSUE TITLE
Le rendu du cahier d'exercice sous Linux produit une police désagréable

### ISSUE THREAD

**Issue by gquintana** [Zenika/zenika-formation-framework#35]
Quand on fait le rendu sous Linux, l'absence de police Helvetica produit un PDF avec une police "narrow" bizarre. Si on enlève Helvetica, c'est bien mieux:

```
body {
  font-family: Helvetica, arial, sans-serif;
```

**Comment by hgwood** [comment]
@gquintana Est-ce toujours d'actualité ?

**Comment by gquintana** [comment]
oui

**Comment by hgwood** [comment]
Ligne en question : https://github.com/Zenika/Formation--Framework/blob/master/styleCahierExercice.css#L2

As-tu une suggestion de correction / une police à suggérer ?

**Comment by gquintana** [comment]
N'importe quelle police à peu près cross-platform: `Arial, sans-serif` par exemple.
Je ne sais plus qu'elle police on utilise dans les slides, mais je n'ai pas de souci avec les slides.
Ou alors on pourrait fournir la police avec les CSS.

**Comment by hgwood** [comment]
Exemple du rendu désagréable (à priori) : http://zen-formation-angularjs.appspot.com/pdf/Zenika-Formation-AngularJs-CahierExercices.pdf
