### ISSUE TITLE
Nouvelle charte graphique

### ISSUE THREAD

**Issue by ldez** [Zenika/zenika-formation-framework#37]
Revoir les elements en fonction de la nouvelle charte

**Comment by ggerbaud** [comment]
[Prez_Commerciale_06_2015.pptx](https://github.com/Zenika/Formation--Framework/files/417/Prez_Commerciale_06_2015.pptx)

Je cite Al
> On ne va pas utiliser toutes les couleurs mais une seule, ceci afin d'être raccord et aussi parce que les slides actuelles sont moches ;)

>Je te mets en pièce jointe un powerpoint (la dernière page du doc ressemble un peu à ce que l'on a) et je vais préparer une page de garde et de chapitrage.

>Et voici le rouge que l'on utilise Rouge : #af1e3a

**Comment by ldez** [comment]
Cool merci.

**Comment by ldez** [comment]
Faut peut-etre supprimer le document vu que le dépôt est public ?

**Comment by ggerbaud** [comment]
Bien vu

**Comment by ggerbaud** [comment]
C'est issue a été implémentée dans la branche #theme_integ
Il reste a bien tester sur de vrai cas, et à marger

**Comment by ggerbaud** [comment]
un bug persiste :cry: 

La génération en pdf via phantom casse tout le design et des éléments graphiques se retrouvent n'importe où.
La génération de pdf de façon manuelle fonctionne quand à elle correctement.

@BenoitAverty, @srevereault et moi même avons jetté un oeil, sans succès

**Comment by olivierhuber** [comment]
Je propose d'intégrer le nouveau thème dès à présent quitte dans un premier temps à continuer de générer les PDF depuis Chrome avec Ctrl-P
On le fait déjà pour la formation Go

**Comment by hgwood** [comment]
Il semble que la branche `theme_integ` a été corrompue par de mauvaises manipulations de git. Elle contient plein de commits qui sont des copies de commit appartenant à `master`. Je vais essayer de démêler ça et ouvrir une PR.

**Comment by hgwood** [comment]
Done : #120.
