### ISSUE TITLE
Remplacement de Grunt par Gulp

### ISSUE THREAD

**Issue by ldez** [Zenika/zenika-formation-framework#48]
Je pense que le remplacement de Grunt par Gulp serait utile pour simplifier les évolutions.

Un exemple est le générateur [gulp-angular](https://github.com/Swiip/generator-gulp-angular) de @Swiip.

Pourquoi je dis ca ?
- Pouvoir avoir un fichier clair et isolé pour chaque tache.
- les plugins sont très puissant et simple de configuration
- utilisation de [gulp-inject](https://www.npmjs.com/package/gulp-inject)
- utilisation de [BrowserSync](https://www.npmjs.com/package/browser-sync) pour le hot reload.
- vive les streams

Je laisse @Swiip compléter pour expliquer pourquoi Gulp c'est mieux.

**Comment by jlandure** [comment]
Bonjour, j'ai un peu de temps sur juillet donc je peux aider si besoin. 
Je connais bien gulp.

**Comment by Swiip** [comment]
Un petit retour d'étude de marché, j'ai fais le tour des seed projects pour Angular2 hier. 70% de Gulp, 0% de Grunt. Les autres 30% c'est varié: Makefile (oui oui), NPM, Webpack...

**Comment by ggerbaud** [comment]
lié à #77

**Comment by hgwood** [comment]
Alternative : #117.

**Comment by hgwood** [comment]
Je clos en faveur de #117 (qui n'exclue pas Gulp si c'est la solution la plus simple).
