### ISSUE TITLE
Problème de margin

### ISSUE THREAD

**Issue by ncuillery** [Zenika/zenika-formation-framework#71]
il y a un problème sur les espaces entre les paragraphes. Ils sont plus étroit que les espaces entre les listes:

Paragraphes:
![capture du 2015-08-14 09 57 04](https://cloud.githubusercontent.com/assets/4425455/9270109/794dcde6-426f-11e5-83db-dbe1bf32b1a4.png)

Listes:
![capture du 2015-08-14 09 59 02](https://cloud.githubusercontent.com/assets/4425455/9270120/8bfbd7bc-426f-11e5-9104-cf4fae925700.png)

Liste = énumération donc pas de séparation

Paragraphe = nouveau sujet --> séparation

Lié à #70

**Comment by hgwood** [comment]
Cela vient du fait que le thème original est conçu pour des slides à puces et se veut aéré. L'espace entre les puces à donc été augmenté, mais pas celui entre les paragraphes.

C'est probablement une erreur d'utiliser les puces dans tous les contextes et on pourrait s'en passer.

https://github.com/Zenika/Formation--Framework/blob/master/reveal/theme-zenika/theme.css#L152

**Comment by ncuillery** [comment]
:+1:

**Comment by gquintana** [comment]
+1 pour homogénéiser paragraphes et puces sur les margins

La margin `0.8.em` par défaut sur les puces est trop important à AMHA

**Comment by hgwood** [comment]
@ncuillery @gquintana Pouvez-vous tester le nouveau thème (#120) pour voir s'il répond à ce problème ?

**Comment by hgwood** [comment]
Je ferme car je pense que le nouveau thème change la donne mais ne pas hésiter à rouvrir si besoin.
