### ISSUE TITLE
Mise en forme du texte

### ISSUE THREAD

**Issue by ncuillery** [Zenika/zenika-formation-framework#72]
![capture du 2015-08-14 10 07 49](https://cloud.githubusercontent.com/assets/4425455/9270203/150c39f2-4270-11e5-9c31-5447379a6a0f.png)
- Le code inline est trop gros (impression donnée par la police à chasse fixe).
- L'italique (simple astérisque) c'est pas en italique :dizzy_face:
- Le gras (double astérisque) est en italique :dizzy_face::dizzy_face::dizzy_face:

Un petit fond gris clair pour le code inline le ferait mieux ressortir aussi.

Lié à #70

**Comment by hgwood** [comment]
Tu supposes qu'une paire d'étoiles en markdown correspond à l'italique et que la double paire est pour le gras mais ce n'est pas le cas. La première est pour `em` et la deuxième est pour `strong`, or le thème Zenika définit *volontairement* `em` comme étant coloré et `strong` comme étant coloré et italique.

Autrement dit : c'est pas un bug c'est une feature. :D

**Comment by ncuillery** [comment]
Ceux qui trouvent ca laid levez le doigt !

:point_up:

**Comment by ncuillery** [comment]
Ok pour l'emphase où le terme est neutre, on a le choix de la mise en avant... par contre, `<strong>` c'est du gras quoi

**Comment by hgwood** [comment]
MDN
> L'élément HTML `<strong>` est utilisé pour donner de l'importance à un texte, cela se traduit généralement par un affichage en gras.

HTML est théoriquement "presentation-free".

La définition originale du thème Zenika pour les slides, écrite par Olivier Croisier, interdit le gras purement et simplement. Mais on a tout à fait le droit de faire évoluer ce thème. Cependant, je ne vois pas l'intérêt et je trouve que la fonctionnement actuel est bien : important = coloré, très important = coloré et italique. La sémantique est simple et évidente.

**Comment by ncuillery** [comment]
Perso, je trouve que le coloré + italique ne ressort pas "plus" que le coloré uniquement...

Plus objectivement, je veux bien que l'on s'approprie un thème avec quelques originalités de mise en forme, mais le fait que le marqueur "italique" ne s'affiche pas en italique et que le marqueur "gras" lui s'affiche en italique, c'est un comble.

**Comment by hgwood** [comment]
Rien en markdown n'est marqueur d'italique ou de gras, car il est impossible générer des `<i>` ou des `<b>` (sauf en écrivant du HTML directement évidemment).

**Comment by hgwood** [comment]
Je reformule : pour écrire en italique ou en gras en markdown, on met des `<i>` et des `<b>`. Les astérisques ne sont pas marqueurs de mise en forme.

**Comment by hgwood** [comment]
Après le thème n'est pas parfait non plus à ce niveau. On utilise `*` pour "important" au lieu de "emphase" et `**` pour "très important" au lieu de "important". J'imagine qu'on pourrait inverser, parce qu'en Français on utilise clairement l'italique pour les emphases.

**Comment by gquintana** [comment]
+1 pour le problème soulevé par @ncuillery 
Pas d'avis sur la meilleure solution

**Comment by hgwood** [comment]
@ncuillery @gquintana Pouvez-vous tester le nouveau thème (#120) pour voir s'il répond à ce problème ?

**Comment by hgwood** [comment]
Je ferme car je pense que le nouveau thème change la donne mais ne pas hésiter à rouvrir si besoin.

**Comment by hgwood** [comment]
Just for the record: the new theme does not change this behavior.
