### ISSUE TITLE
Mise en forme des blocs de code

### ISSUE THREAD

**Issue by ncuillery** [Zenika/zenika-formation-framework#73]
Le gros cadre rouge pleine largeur sur les blocs de code est un peu "agressif". Des fois on veut poser un bloc de code pour profiter de l'indentation sans forcément que ca apparaisse comme le truc le plus important du slide.

Exemple ci dessous : le 2eme bloc de code OK, c'est effectivement un bloc de code. Mais le 2ème, c'est un prototype de méthode, je ne veux pas que ca ne ressorte comme un bloc de code.

![capture du 2015-08-14 10 53 15](https://cloud.githubusercontent.com/assets/4425455/9271751/a6e29d74-427c-11e5-9826-778131280ae9.png)

Lié à #70

**Comment by hgwood** [comment]
Quelle solution proposes-tu ?

**Comment by ncuillery** [comment]
Une mise en forme plus discrète.

```
A la Github quoi
```

**Comment by hgwood** [comment]
Ça me parait être une bonne idée.

Au niveau du code c'est ici : https://github.com/Zenika/Formation--Framework/blob/master/reveal/theme-zenika/theme.css#L171

**Comment by gquintana** [comment]
Si ca peut aider: https://github.com/Zenika/Formation--Framework/issues/43

**Comment by gquintana** [comment]
Dans le framework 0.4.1, le code semble plus en gras, ce qui le met encore plus en relief:

![bold-code](https://cloud.githubusercontent.com/assets/755587/9441349/db55c9a4-4a75-11e5-9cdd-1c7bfa6f40cf.png)

**Comment by hgwood** [comment]
@ncuillery @gquintana Pouvez-vous tester le nouveau thème (#120) pour voir s'il répond à ce problème ?

**Comment by hgwood** [comment]
Je ferme pour le moment mais ne pas hésiter à rouvrir si besoin.
