### ISSUE TITLE
Ajouter un zip disponible en download sur le site appspot

### ISSUE THREAD

**Issue by jlandure** [Zenika/zenika-formation-framework#97]
Ca serait pas mal d'avoir le zip qui est utilisé avec le déploiement continu pour les personnes qui ont peur de perdre le net.
Dans le zip, nous aurions : la page web reveal + les PDFs

**Comment by jlandure** [comment]
Tant que j'y pense, je me demande s'il ne faudrait pas avoir les pdfs dans la formation directement... Comme ça pas besoin de faire de zip et n'importe qui peut regarder le pdf. A chaque build ou release, on fait un webhook pour commiter le pdf généré.
Ca libérerait le fait d'avoir plusieurs points d'entrée : le `drive` + github.
Là, on irait tout mettre sur github... même nos formations partenaires.

**Comment by hgwood** [comment]
Je ne suis pas sûr de te suivre vu que les PDF sont dispo sur les mini-site.

**Comment by jlandure** [comment]
Le but premier étant d'être offline, l'action de `checkout` le projet git fait qu'on devient offline...
Après je suis d'accord, les mini-sites suffisent mais j'essaie de retrouver le besoin de cette issue ^^

**Comment by hgwood** [comment]
Je crois que l'issue c'est :
- un formateur veut utiliser les slides en ligne (mini-site) pour faire la formation
- mais problème s'il perd le net !
- alors on lui donne un zip avec le contenu pour qu'il puisse l'ouvrir sur son poste

Sauf que, les slides HTML ne peuvent pas être ouvertes en local sans serveur, donc quand on dit "ouvrir sur son poste" on parle du PDF. Et si on parle des PDF, pas besoin de faire un zip car on peut simplement télécharger les 2 PDF et on a tout ce qu'il faut.

Non ?

**Comment by jlandure** [comment]
ok bah on ferme. ^^
