### ISSUE TITLE
Versionner les pdf

### ISSUE THREAD

**Issue by emilevauge** [Zenika/zenika-formation-framework#98]
Je pense qu'il serait intéressant de versionner les supports pdf générés, en suffixant par la date de commit ou par le sha1 du commit. De nombreuses erreurs de versions sont commises du fait de la difficulté actuelle à savoir à quelle version correspond un pdf.

**Comment by jlandure** [comment]
Je pense que ça serait intéressant d'avoir la version issue du package.json... pour la partie "release" (déployé en "release")
sinon oui un numéro de version dans tous les cas pour ce qui ressort du "master" (déployé en "current")
